### ISSUE TITLE
build video is no longer available

### ISSUE THREAD

**Issue by phonovision** [openpower-cores/a2o#17] opened 2022-01-07 22:02 UTC
Build video linked in [/rel/doc/a2_build_video.md](https://github.com/openpower-cores/a2o/blob/master/rel/doc/a2_build_video.md) is no longer available.

**Comment by openpowerwtf** [comment] 2022-03-03 01:16
This is a duplicate of #16.

**Closed as completed by openpowerwtf** 2022-03-03 01:16 UTC
Labels: duplicate
